# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: sinatra-crud-development

test:
  adapter: postgresql
  database: sinatra-crud-test

production:
  adapter: postgresql
  database: sinatra-crud-production
